server.port=8082

spring.application.name=smart-search-agent

spring.ai.openai.base-url=http://litellm:4000
spring.ai.openai.api-key=no-key-needed
spring.ai.openai.chat.options.model=gemini-flash

spring.ai.retry.max-attempts=1
spring.ai.openai.embedding.options.model=nomic-embed-text

spring.ai.vectorstore.qdrant.host=qdrant
spring.ai.vectorstore.qdrant.port=6334
spring.ai.vectorstore.qdrant.collection-name=doc-query-docs
spring.ai.vectorstore.qdrant.initialize-schema=false
